### PR TITLE
ADD : possibility to use proxy configuration, see docs.python-requests.org/en/master/user/advanced/ for more info

### PR DESCRIPTION
**Pull request by foudezic63**

### CODE REVIEW

**Comment by mkorkmaz** [comment]
@foudezic63 nice addition buddy. Would you consider to add tests for this request before merge?

**Comment by foudezic63** [comment]
Thank you,

Hard to test no ? I mean it would need to have a universal proxy address,
i'm not sure that it exists.


Le jeu. 13 sept. 2018 13:43, Mehmet Korkmaz <notifications@github.com> a
écrit :

**Comment by mkorkmaz** [comment]
@foudezic63 We usually expect contributors to include the tests for the code they wrote. If you don't have time, it's ok. I can write the tests when i have the time. Thanks again for your contribution.

**Comment by foudezic63** [comment]
Sorry, do not misunderstand me :)
I wrote a test with a free proxy configuration found with google
Yet I cannot run it on my side because i'm already working behind a proxy :)

I can only tell you that with the proxy i'm working behind, it works ^^'



Le jeu. 13 sept. 2018 à 22:47, Mehmet Korkmaz <notifications@github.com> a
écrit :

**Comment by mkorkmaz** [comment]
@foudezic63 I maintain my open source libraries on my spare time, most of the open source developers are like this. We may not have time to take immediate action. That's why we need code with test. If test passes, we only check the code written. If that's ok, we merge. I didn't intent to make you uncomfortable. Just made my statement :) Anyway, test failed on travisci but it is my job to make it work if the problem is just configuration.

Thank you again.

**Pull request merged**
